### ISSUE TITLE
Support for non-string data types

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#1]
Today, all data is stored as strings. With this enhancement, we want to be able to support primitive data types.

**Requirements**

1. We want to be able to support primitive data types in clickhouse: `numbers`, `booleans`, `datetime`, and `null` types. We will _not_ change how we handle arrays and maps.
2. In each user's config, we should have a new config value, `string_types`. If this is false, then the code will use our new typing logic. If it is true, then we will continue to store all data as strings.
4. When creating new columns, they should not be nullable in clickhouse. They should have a default zero value.
5. We should attempt to determine if string columns are formatted as dates. If so, we should create columns as datetime.
6. We should never fail to insert data. If the types are completely incompatible (for example, an Int and Array type) then we should default to the zero value.

**Guidelines**
- There are many ways to have Clickhouse read JSON data. Clickhouse has a JSONEachRow format which could be useful since it automatically infers types. Clickhouse also has guidelines for JSON [here](https://clickhouse.com/docs/en/integrations/data-formats/json). 
- This set of features should be broken into small incremental self-contained PRs.
- Please include automated tests.
- I have started this work [here](https://github.com/scratchdata/ScratchDB/pull/53), but the code is incomplete, does not compile, and behaves differently than the above requirements.

**Comment by chumaumenze** [comment]
Can you share a example of a `null` type? Are they the same as `Nullable(Nothing)`? I assumed  something like `Nullable(Int8)` but since columns should not be nullable but have default values, it is difficult to determine the nature of these type.

Per datetime requirement, Clickhouse will infer dates and datetimes from strings but it requires additional configuration on the server to be able to parse more formats. By default, it can parse only basic formats: `time.DateTime` and `time.DateOnly`. Setting the parameter `date_time_input_format` to `best_effort` will extend the functionality to include all ISO 8601 formats. The alternative would be to format the date fields in the NDJSON to a basic format thereby losing precision. I prefer the both but formatting to an extended format.

Item 5, still WIP. I have to figure out how to segregate incompatible data and handle accordingly.

cc: @poundifdef

**Comment by poundifdef** [comment]
Thank you. 

1.  I agree, there is a contradiction between null vs default values. For now, let's remove the requirement to have nullable columns and make everything non-nullable.
2. I am fine with using `best_effort` in clickhouse. We can make this behavior configurable in the future.
3. re: Item 5, let's handle that in a separate PR and then we can have additional discussion there.
