### ISSUE TITLE
Postgrest compatibility

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#25]
Could we support postgrest (https://postgrest.org/en/stable/) query syntax? This would be a huge usability win.

**Comment by SrijanSriv** [comment]
Hi. I wanted to grow this issue as a conversation.

I'm taking it that the syntax change will currently consist of very basic querying for info and not modifying the data itself(maybe stay away from views as well?). So for example, the current way of querying the complete table `my_table` that looked like this:

`http://localhost:3000/query?q=select * from my_table`

Shall look like this:

`http://localhost:3000/my_table`

Subsequent filtering on the basis of columns being a series of query strings.

I wonder if the idea of viewing the result as an html table will be a part of the query string still, or part of the path somehow? Because a request such as:

`http://localhost:3000/my_table?format=html`

Is the same as filtering `my_table` according to the format column.

**Comment by TC4Y-777** [comment]
Vertical filtering can be done by using the query param 'select'.
`http://localhost:3000/my_table?select=format`

Horizontal filtering can seem to be similar as when specifying the format, but we can use special operators for that.
For example, 

`http://localhost:3000/my_table?format=eq.html` would return result from my_table that has the value 'html' in the format column

`http://localhost:3000/my_table?format=html` would return the result as an html table

**Comment by TC4Y-777** [comment]
Reference: https://postgrest.org/en/stable/references/api/tables_views.html#tables-and-views

**Comment by TC4Y-777** [comment]
It seems that postgrest-like query syntax is completely feasible here.

I think that we can improve some aspects of the postgrest syntax. Rather than specifying in the headers what all columns need to be returned after a POST operation, we can go towards a more GraphQL way.

What are your thoughts on that?

**Comment by SrijanSriv** [comment]
> `http://localhost:3000/my_table?format=eq.html` would return result from my_table that has the value 'html' in the format column
 `http://localhost:3000/my_table?format=html` would return the result as an html table
 
 Ah! Operators can help distinguish filtering from any specific formatting
 
 > I think that we can improve some aspects of the postgrest syntax. Rather than specifying in the headers what all columns need to be returned after a POST operation, we can go towards a more GraphQL way.
 
 While its true that `return=representation` will return all the columns after a POST request, we don't have to alter the header further and follow the [Vertical Filtering](https://postgrest.org/en/stable/references/api/tables_views.html#v-filter) rules. I would agree that GraphQL's structure is better, but that sounds like it would defeat the purpose of usability, mixing two formats?

**Comment by poundifdef** [comment]
Thank you all for the discussion! 

- We do not need to support `?format=html` for postgrest compatibility. 
- There are probably 2 tickets here: supporting SELECT and supporting INSERT
- The goal is to be compatible with existing postgres clients and libraries
- We should be able to support basic filters
- We can ignore JOINs for now since clickhouse does not support foreign key relationships. But we can create a ticket to look at this in the future (for example, maybe we could use column descriptions to indicate foreign key relationships?)

**Comment by SrijanSriv** [comment]
> We do not need to support ?format=html for postgrest compatibility.

Right, the existing syntax will be left as is, all the while enabling a separate syntax as well.

> Could we could use a base path, such as /postgrest/my_table so that there is a clear separation of postgrest vs regular functionality?

That will be a much better option.

> We can ignore JOINs for now since clickhouse does not support foreign key relationships. But we can create a ticket to look at this in the future (for example, maybe we could use column descriptions to indicate foreign key relationships?)

I believe postgrest has definitions for [JOINs](https://postgrest.org/en/stable/references/api/resource_embedding.html) as well. Since it needs other things to get in order, its enough to create a ticket with some description probably.

**Comment by TC4Y-777** [comment]
I will work on it.
